core/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@home')->name('home');
Route::get('notice', 'FrontendController@notice')->name('notice');
Route::get('office-order', 'FrontendController@officeOrder')->name('office-order');
Route::get('notice-details/{id}', 'FrontendController@noticeDetails')->name('notice-details');
Route::get('dig-message', 'FrontendController@messageFormDig')->name('dig-message');
Route::get('activities', 'FrontendController@activities')->name('activities');
Route::get('recent-photo', 'FrontendController@recentPhoto')->name('recent-photo');
Route::get('photo-gallery', 'FrontendController@photoGallery')->name('photo-gallery');

Route::get('photo-gallery/{id}', 'FrontendController@viewGallery')->name('view-gallery');

Route::get('about', 'FrontendController@about')->name('about');
Route::get('mission', 'FrontendController@mission')->name('mission');
Route::get('vision', 'FrontendController@vision')->name('vision');
Route::get('history', 'FrontendController@history')->name('history');
Route::get('organogram', 'FrontendController@organogram')->name('organogram');
Route::get('dig-list', 'FrontendController@digList')->name('dig-list');
Route::get('staff', 'FrontendController@staff')->name('staff');
Route::get('sacrifices', 'FrontendController@sacrifices')->name('sacrifices');
Route::get('crime-statistics', 'FrontendController@crimeStatistics')->name('crime-statistics');
Route::get('noc', 'FrontendController@noc')->name('noc');
Route::get('tender', 'FrontendController@tender')->name('tender');
Route::get('download', 'FrontendController@download')->name('download');
Route::get('citizen-charter', 'FrontendController@citizenCharter')->name('citizen-charter');

Route::get('sp/{id}', array('uses'=>'FrontendController@sp'))->name('district');
Route::get('pbi', 'FrontendController@pbi')->name('pbi');

//Route::get('sp-rajshahi', 'FrontendController@spRajshahi')->name('sp-rajshahi');
//Route::get('sp-chapai', 'FrontendController@spChapai')->name('sp-chapai');
//Route::get('sp-naogaon', 'FrontendController@spNaogaon')->name('sp-naogaon');
//Route::get('sp-natore', 'FrontendController@spNatore')->name('sp-natore');
//Route::get('sp-pabna', 'FrontendController@spPabna')->name('sp-pabna');
//Route::get('sp-sirajganj', 'FrontendController@spSirajganj')->name('sp-sirajganj');
//Route::get('sp-bogra', 'FrontendController@spBogra')->name('sp-bogra');
//Route::get('sp-joypurhat', 'FrontendController@spJoypurhat')->name('sp-joypurhat');
Route::get('sp-rrf', 'FrontendController@spRrf')->name('sp-rrf');
Route::get('thana/{id}', 'FrontendController@thana')->name('thana');
Route::get('contact-us', 'FrontendController@contactUs')->name('contact-us');


//Route::get('information-instruction', 'FrontendController@informationIns')->name('information-instruction');
//Route::get('informer-info', 'FrontendController@informerInfo')->name('informer-info');
Route::get('otp-info', 'FrontendController@otpInfo')->name('otp-info');
Route::get('help-with-information', 'FrontendController@informationHelp')->name('information-help');
//Route::get('/matchOtpInfo', 'OtpController@matchOtpInfo');

Route::resource('otp', 'OtpController');
//Route::get('complaint-instruction', 'FrontendController@complaintIns')->name('complaint-ins');
//Route::get('complainer-info', 'FrontendController@complainerInfo')->name('complainer-info');
Route::get('otp-submit', 'FrontendController@otpSubmit')->name('otp-submit');
Route::get('complaint-box', 'FrontendController@complaint')->name('complaint');
//Route::get('/matchOtp', 'OtpController@matchOtp');


Route::get('wanted', 'FrontendController@wanted')->name('wanted');
Route::get('useful-links', 'FrontendController@links')->name('useful-links');
Route::get('jurisdiction-map', 'FrontendController@jurisdictionMap')->name('jurisdictionMap');



//News Portal Routes
Route::get('/news', 'FrontendController@news');
Route::get('/news/{id}', 'FrontendController@view_news');
Route::get('/news/category/{id}', 'FrontendController@category_news');
Route::get('news/district/{id}', 'FrontendController@district_news');

//Backend Routes
Route::get('frontend/layouts/partial/head', 'FrontendController@test');

//Received messages route for storing messages to database
Route::post('/save', 'ContactsController@save');
Route::get('/matchOtpInfo', 'ContactsController@matchOtpInfo')->name('matchOtpInfo');
Route::get('/matchOtpCom', 'ContactsController@matchOtpCom')->name('matchOtpCom');

//Route::get('/admin', 'LoginController');
//Route::get('/admin/dashboard', 'HomeController@index')->name('dashboard');

Route::group(['middleware'=> 'auth'], function (){

    Route::get('admin/news/publish/{id}', array('uses' => 'NewsController@publishNews'));
    Route::get('admin/news/unpublish/{id}', array('uses' => 'NewsController@unpublishNews'));
    Route::get('admin/news/destroyImage/{id}', array('uses'=>'NewsController@destroyImage'));
    Route::get('admin/news/allpublishednews', array('uses'=>'NewsController@allpublishednews'))->name('all-published-news');
    Route::get('admin/news/allunpublishednews', array('uses'=>'NewsController@allunpublishednews'))->name('all-unpublished-news');

    Route::get('admin/tender/publish/{id}', array('uses' => 'TenderController@publish'));
    Route::get('admin/tender/unpublish/{id}', array('uses' => 'TenderController@unpublish'));

    Route::get('admin/notice/publish/{id}', array('uses' => 'NoticeController@publish'));
    Route::get('admin/notice/unpublish/{id}', array('uses' => 'NoticeController@unpublish'));

    Route::get('admin/gallery/destroyImage/{id}', array('uses' => 'GalleryController@destroyImage'));

    Route::get('admin/contacts/complaints', array('uses' => 'ContactsController@complaints'))->name('admin-complaint');
    Route::get('admin/contacts/info', array('uses' => 'ContactsController@information'))->name('information');

    Route::get('admin/index', array('uses' => 'DashboardController@index'))->name('dashboard');
    Route::resource('/admin/settings', 'SettingsController');
    Route::resource('admin/slider', 'SliderController');
    Route::resource('admin/users', 'UsersController');
    Route::resource('admin/roles', 'RolesController');
    Route::resource('admin/permissions', 'PermissionsController');
    Route::resource('admin/categories', 'NewsCategoryController');
    Route::resource('admin/news', 'NewsController');
    Route::resource('admin/district', 'DistrictController');
    Route::resource('admin/thana', 'ThanaController');
    Route::resource('admin/dig', 'DigController');
    Route::resource('admin/tender', 'TenderController');
    Route::resource('admin/notice', 'NoticeController');
    Route::resource('admin/noc', 'NocController');
    Route::resource('admin/services', 'ServicesController');
    Route::resource('admin/staff', 'StaffController');
    Route::resource('admin/gallery', 'GalleryController');
    Route::resource('admin/sp', 'SpController');
    Route::resource('admin/contacts', 'ContactsController');
    Route::resource('admin/jurisdictionContacts', 'JurisdictionContactsController');
    Route::resource('admin/mostWanted', 'MostWantedController');
    Route::resource('admin/downloadable', 'DownloadableController');
    Route::resource('admin/links', 'LinksController');
    Route::resource('admin/crime-statistics', 'CrimeStatisticsController');
});
Auth::routes();

core/resources/views/admin/crime/index.blade.php
@extends('layouts.master')

@section('title')

    <section class="content-header">
        <div class="row">
            <div class="col-md-6">
                <h1>Crime statistics</h1>
            </div>
        </div>
        <ol class="breadcrumb">
            <li>
                <a href="{{ route('dashboard') }}">
                    <i class="fa fa-fw fa-home"></i>Dashboard
                </a>
            </li>
            <li>
                <a href="#">Crime statistics</a>
            </li>
        </ol>
        <div class="flash-message">
            @foreach (['danger', 'warning', 'success', 'info'] as $msg)
                @if(Session::has('alert-' . $msg))

                    <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                @endif
            @endforeach
        </div> <!-- end .flash-message -->
    </section>

@endsection

@section('content')
    <section class="content paddingleft_right15">
        <div class="row">
            <div class="col-lg-12">
                <!-- First Basic Table strats here-->
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            <i class="fa fa-fw fa-bell-o"></i>
                            Crime statistics details
                        </h3>
                        <span class="pull-right">
                            <i class="fa fa-fw fa-times removepanel clickable"></i>
                            <i class="fa fa-fw fa-chevron-up clickable"></i>
                        </span>
                    </div>
                    <div class="panel-body">
                        @if($statistics)
                            @foreach($statistics as $statistic)
                                <div class="col-md-4">
                                    <div class="table-responsive">
                                        <table class="table" id="table">
                                            <tr>
                                                <th class="text-left">Robbery</th>
                                                <td class="text-center">{{ $statistic->robbery }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-left">Murder</th>
                                                <td class="text-center">{{ $statistic->murder }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-left">Speedy trial</th>
                                                <td class="text-center">{{ $statistic->speedy_trial }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-left">Riot</th>
                                                <td class="text-center">{{ $statistic->riot }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-left">Women & child Repression</th>
                                                <td class="text-center">{{ $statistic->women_child }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-left">Kidnapping</th>
                                                <td class="text-center">{{ $statistic->kidnapping }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-left">Police assault</th>
                                                <td class="text-center">{{ $statistic->police_assault }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-left">Burglary</th>
                                                <td class="text-center">{{ $statistic->burglary }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-left">Theft</th>
                                                <td class="text-center">{{ $statistic->theft }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-left">Other</th>
                                                <td class="text-center">{{ $statistic->other }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-left">Total</th>
                                                <td class="text-center">{{ $statistic->total }}</td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                                <div class="col-md-4 col-md-offset-2">
                                    <div class="text-center">
                                        <br><br>
                                        <p><b>Note : </b>You are not allowed to create more than one crime statistics. If you try, you might face inconceivable errors. Please edit this one and make changes.</p><br><br>
                                        <a href="{{ route('crime-statistics.edit', $statistic->id) }}" class="btn btn-primary btn-lg btn-block">Edit</a>

                                        {{--<button class="btn btn-danger btn-lg" data-toggle="modal" data-target="#deleteModal{{$statistic->id}}">Delete</button>--}}

                                        {{--<div class="modal fade" id="deleteModal{{$statistic->id}}" role="dialog">--}}
                                            {{--<div class="modal-dialog modal-sm">--}}
                                                {{--<div class="modal-content">--}}
                                                    {{--<div class="modal-header">--}}
                                                        {{--<button type="button" class="close" data-dismiss="modal">&times;</button>--}}
                                                        {{--<h4 class="modal-title">Delete crime statistics details</h4>--}}
                                                    {{--</div>--}}
                                                    {{--<div class="modal-body">--}}
                                                        {{--<p>Are you sure, you want to delete this statistics?</p>--}}
                                                    {{--</div>--}}
                                                    {{--<div class="modal-footer">--}}
                                                        {{--{!! Form::open(['method'=>'DELETE', 'action'=>['CrimeStatisticsController@destroy', $statistic->id]]) !!}--}}
                                                        {{--<button type="submit" class="btn btn-danger" style="float: left;">Yes</button>--}}
                                                        {{--{!! Form::close() !!}--}}
                                                        {{--<button type="button" class="btn btn-default" data-dismiss="modal" style="float: right; margin-left: 15px;">Cancel</button>--}}
                                                    {{--</div>--}}
                                                {{--</div>--}}
                                            {{--</div>--}}
                                        {{--</div>--}}
                                    </div>
                                </div>
                            @endforeach
                        @endif
                    </div>
                </div>
            </div>
    </section>
@endsection